### ISSUE TITLE
email / password registration should not require firstname or lastname

### ISSUE THREAD

**Issue by alarner** [alarner/react-express-template#14]

**Comment by dominathan** [comment]
From a cursory glances, it looks like you have notNullabe on firstName in your knex migrations 

```
                 t.string('firstName').notNull();
        t.string('lastName').nullable();
        t.string('email').nullable();
```

 Happy to take a stab at it.  I've been using a pretty similar stack minus bookshelf so I'm happy to take a stab at some of these.

**Comment by alarner** [comment]
@dominathan Yes that would be awesome! There might also be some validation code in the routes/auth.js file for the `.post('/register/ ...)` but I can't quite remember, so maybe take a look in there too.

**Comment by dominathan** [comment]
Don't see any validators on firstname,lastname in the auth routes, nor in the UserModel

**Comment by dominathan** [comment]
Close that puppy out!

**Comment by alarner** [comment]
Thanks for your help!
