### ISSUE TITLE
After the dev server boots up for the first time display a message notifying how to load the page

### ISSUE THREAD

**Issue by alarner** [alarner/react-express-template#30]
After running the `npm run dev` command it's not clear that the server is running successfully because the last message says: "Browserify: Bundle successful"

After:
1. the server has started
2. sass has compiled
3. js has compiled

Add the following message:
`Server is running at server_address_goes_here`
where server_address_goes_here would be something like `http://127.0.0.1:3000/` or whatever depending on which host and port the server is running on.

**Comment by tphdev** [comment]
@alarner 

Submitted a [PR](https://github.com/alarner/perk/pull/38) for this to be merged on the **start-script** branch. Also should note that I attempted to knockout the [NODE_ENV](https://github.com/alarner/perk/issues/34) issue in the same PR. 

If those should be two separate PR's for next time lmk :)
