### ISSUE TITLE
Generator for session secret

### ISSUE THREAD

**Issue by beaulm** [alarner/react-express-template#49]
It would be super sweet to either have the session secret filled in by default with a random, secure value, or to have a CLI tool to generate one for me.

**Comment by alarner** [comment]
Great idea! FYI: This feature request will likely have a dependency of #7 before it can be done.

**Comment by alarner** [comment]
Now that #7 is done I'm working on this.

**Comment by alarner** [comment]
@beaulm do you want to do a quick code review of #97 ?

**Comment by alarner** [comment]
Closed in #97
