### ISSUE TITLE
Default logger config causes error

### ISSUE THREAD

**Issue by alarner** [alarner/react-express-template#73]
The default logger config file lists which level of error should show which color when displayed to the console. Unfortunately there is no `orange` color, so when a warning is logged, it throws an error. To fix this we should change `config/logging.js` to look something like this (setting error to bgRed and warn to red):

``` js
// Options for winston logger
// https://github.com/winstonjs/winston
module.exports = {
    level: 'info',
    transports: [
        new (require('winston').transports.Console)({
            handleExceptions: true,
            humanReadableUnhandledException: true,
            colorize: true,
            prettyPrint: true
        })
    ],
    colors: {
        error: 'bgRed',
        warn: 'red',
        info: 'blue',
        verbose: 'purple',
        debug: 'yellow',
        silly: 'pink'
    }
};
```

**Comment by hammour** [comment]
fixed on Change const let logger #71 pull request
