### ISSUE TITLE
Postgres command not working - it lives somewhere else on my computer

### ISSUE THREAD

**Issue by m2mathew** [alarner/react-express-template#91]
As I followed along with the docs and the [video #1](http://perkframework.com/v1/video-reel/01-up-and-running.html), I was unable to use this command to start my postgres server. 

`launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`

The solution so eloquently given to me by @alarner was to run **`brew info postgres`**. At the bottom of this info stream was the magical command ✨  to start up postgres on my machine. As this will likely help others, it might be wise to include this brew command for other Perk-ers to use. 😜 

`brew services start postgresql` (and also `brew servcies start redis`)

**Comment by m2mathew** [comment]
[PR created here](https://github.com/alarner/perk-docs/pull/50) to add these commands to the docs.

**Comment by alarner** [comment]
PR merged!
