### ISSUE TITLE
Duplicate Link under the 2nd video

### ISSUE THREAD

**Issue by m2mathew** [alarner/react-express-template#93]
On the page for the [second video](http://perkframework.com/v1/video-reel/02-modifying-the-homepage-view.html), there are two links labeled 

> Code (GitHub)

The first link takes a user to the page here → http://perkframework.com/v1/api/views.html#changing-templating-engines

The second link takes a user to the correct page with code from the current video.

Might just need a text change there. 🌴

**Comment by alarner** [comment]
Thanks for the heads up @m2mathew. If you're interested in making a PR this might be [the file](https://github.com/alarner/perk-docs/blob/master/src/v1/video-reel/02-modifying-the-homepage-view.md) that needs some ❤️. If not I'll try and get to this soon :)

**Comment by m2mathew** [comment]
Just forked and working on it. 🔨  Always good to document the issue, too. The more history the better!

**Comment by m2mathew** [comment]
**[PR created](https://github.com/alarner/perk-docs/pull/49)** to right this wrong! 😄
